### ISSUE TITLE
Proposition : simplifier les modèles de lecture (query)

### ISSUE THREAD

**Issue by sroccaserra** [1024pix/pix#649]
Je réfléchis à comment simplifier nos modèles de lecture, suite à :
- la constatation qu'on utilise parfois un même modèle de lecture pour deux ou trois usages différents avec des sous-ensembles distincts de champs vides, ce qui rend ledit modèle flou
- [cet article](https://matthiasnoback.nl/2019/07/dividing-responsibilities-part-1/) sur la séparation entre modèles de lecture et modèles d'écriture
- une discussion avec des collègues (voir ci-dessous)

Je propose qu'on explore ensemble la notion de modèles de lecture, et notamment la possibilité :
- d'avoir plus de modèles de lecture que de modèles d'écriture
- d'avoir des modèles de lecture spécifiques à certaines vues
- de ranger la déclaration de modèles de lecture spécifiques à des vues ailleurs que dans le répertoire domain, afin de mieux les identifier, d'avoir une couche en moins à implémenter pour ces modèles (la simplification est là) et parce-qu'une vue de ce type est entre métier et application

Vous en pensez quoi ?

**Comment by sroccaserra** [comment]
La discussion (anonymisée) qui m'avait intéressé :

> **Thomas**
> Je me pose la question suivante : comment j’organise mes modèles de lecture et d’écriture ?
> en gros, j’ai une même classe qui sert pour un use case de lecture et pour ma command
> hors j’ai besoin d’information pour ma commande qui ne sont pas nécessaire pour la lecture
> je veux donc avec 2 modèles (classes) distinctes. Mais comment je les nomme et / ou organise ?
> mon application commence à migrer vers du CQRS
> est-ce que je splitte mon domaine en command et query ?
> 
> **Eric**
> Est ce que le split command/query est au dessus ou en dessous du split infra/domain?
> 
> **Nathan**
> j'aurais d'emblée créé 2 packages read et write par ex, avec l'arbo que tu veux dedans, quitte à ce que tes modèles aient le même nom
> faute de mieux niveau nommage, séparer et nommer sont 2 problématiques différentes
> 
> **Mathieu**
> potentiellement, il n'ya pas d'infra/domain dans la partir query
> je rectifie mon message : il n'y a pas de domain côté Query
> en étant extrême, tu pourrais faire ta requête SQL directement dans ton use-case
> 
> **Nathan**
> on n'est pas chez les sauvages non plus, hein ^^
> mais effectivement, ton "modèle" de lecture peut très bien ne pas résider dans une couche domain
> 
> **Mathieu**
> pour moi le modèle côté query n'est pas du domain mais de la vue, c'est tout l'intérêt du CQRS (d'avoir 2 modèles)
> donc si je vois un package domain côté query, ce serait un smell
> 
> **Nathan**
> après, tu mets ça dans un package "read/model", ça ne me choque pas
> read, et dedans model
> 
> **Thomas**
> ok, merci pour vos réponses

**Comment by jonathanperret** [comment]
Super intéressant, j'aimerais voir un exemple de ce que ça donnerait dans le code de Pix.

**Comment by sroccaserra** [comment]
Voir aussi : #1255

**Comment by sroccaserra** [comment]
On a eu une discussion intéressante à ce sujet sur la PR #1323, voilà ce que j'en ai retenu.

----

Pb : mais alors s'il y a plein de read models, dans un contexte Web SPA front + API back, ça veut dire qu'on va multiplier les requêtes repository, les sérialiseurs API, les routes API et les modèles front ?

Oui, créer de nouveaux objets qui traversent beaucoup de tranches du hamburger peut avoir un coût plus grand qu'ajouter un champs à un objet existant. Mais ça a aussi un bénéfice : celui de rendre explicite l'usage sur toute la chaîne. Si on ne le fait pas, nos usages sont dilués et entremêlés dans des gros objets. C'est le bénéfice de ranger les usages dans de petits objets.

Ce coût de séparer les objets est aussi moins grand qu'on le croit, car la simplification tentante d'ajouter un champs à un objet existant (avoir des data models "unifiés" et utilisés par beaucoup d'usages différents) a lui aussi un coût. Ce coût un peu caché est en général d'ajouter des "if" dans le comportement et la présentation. Accepter le coût de ne pas avoir de data models unifiés permet en général de supprimer ces "if".

Note importante : on ne s'interdit pas d'utiliser le même read model pour deux usages proches, on s'autorise des compromis.

Autre remarque, si le nombre de read models explose, c'est que nos usages explosent : on pourrait avoir la même action au niveau application : séparer des usages différents dans des contextes différents, voire dans des applications différentes.

**Comment by EGI-OCTO** [comment]
Discussions sur le sujets eu à l'oral lors de la revue de la PR #1323 : 

- [ReadModel versus objet du domain local au context](https://github.com/1024pix/pix/pull/1323/files/c04bb30fd71dabbfc71c7ca376c36ee8b4c2c73f#r419401672)

 - [L'utilisation de ReadModels rend parfois obsolète la couche usecase](https://github.com/1024pix/pix/pull/1323/files/c04bb30fd71dabbfc71c7ca376c36ee8b4c2c73f#r419413664)

**Comment by jbuget** [comment]
> Super intéressant, j'aimerais voir un exemple de ce que ça donnerait dans le code de Pix.

Y a un exemple qui est passé mais je n'ai pas eu le temps de requérir un ADR d'expérimentation que la PR #1286 était déjà mergée 😢

**Comment by sroccaserra** [comment]
Ah oui intéressant, on peut regarder la PR #1286 et même aller plus loin : se passer du usecase et sortir les readmodels du domaine.

**Comment by sroccaserra** [comment]
Un avantage dont on a aussi discuté : sortir les read models du domaine permet de reléguer la pagination hors du métier, dans beaucoup de cas c'est des considérations de présentation + infra.

**Comment by sroccaserra** [comment]
Voir aussi : #1257

**Comment by sroccaserra** [comment]
Autre exemple de complexité apportée par avoir des gros objets et supprimée si on a des petits objets cohésifs : si on a des agrégats petits et cohésifs, on peut aussi avoir des repository beaucoup plus simples, avec un get, un find, un upsert d'agrégat complet et cohérent et un delete. Mais pour un gros objet par exemple un user qui inclue des CGUs ça ne fonctionne pas bien, faire un upsert de user complet pour accepter des CGU = meh. Ça conduit à avoir des repositories avec plein de méthodes spécifiques.

**Comment by MathieuGilet** [comment]
Lorsque l'on parle de sortir les read models du domaine, est-ce que ça signifie que les usecases continueront à retourner des objets du model, comme un User et ses dépendances, et que le serializer (ou autre) sera chargé de transformer le User en un read model (comme UserDetailForAdmin dans la PR https://github.com/1024pix/pix/pull/1286)?

**Comment by EGI-OCTO** [comment]
> Lorsque l'on parle de sortir les read models du domaine, est-ce que ça signifie que les usecases continueront à retourner des objets du model, comme un User et ses dépendances, et que le serializer (ou autre) sera chargé de transformer le User en un read model (comme UserDetailForAdmin dans la PR #1286)?

Y'a quelques info dans [cette réponse](https://github.com/1024pix/pix/issues/649#issuecomment-623449603) qui peuvent aider à comprendre ce qui suit.

Il y a deux cas "simples":
- Un endpoint de `Query` pure : par exemple `GET /invoices?since=2020-05-07` qui retourne la liste de toutes les factures depuis une certaine date. Ici on ne fait que de la redescente d'informations. Il n'y aura aucun effet de bord sur le SI (par simplicité : on n'ajoute/modifie/supprime aucune données en base). Donc hormis un contrôle d'accès et une validation de surface du format de date, il n'y aura aucune logique métier à appliquer. Dans ce cas il est pertinent de ne pas passer par un `usecase` et d'appeler dans le `controller` directement quelque chose qui retourne un _ReadModel_ (on peut appeler ce quelque chose `repository` ou alors quelque chose d'autre histoire de distinguer ce qui retourne des `ReadModel` de ce qui retourne des objets du domain). C'est ce qui a été fait dans [ce controller](https://github.com/1024pix/pix/blob/b8572941a24f783fd96899424981da6bd9028728/api/lib/application/sessions/session-controller.js#L17).

- Un endpoint de `Command` pure : par exemple `/issue-invoice` qui émet une facture. On créer un effet de bord dans le SI (par simplicité : on crée par exemple une nouvelle ligne dans la table _invoices_) et on est uniquement intéressé par le fait que cette action ait réussie ou échouée. Ici, si le _usecase_ remonte les éventuelles anomalies par mécanisme d'exceptions, il peut très bien ne rien retourner du tout. Si pas d'exception on retourne `200`, si il y a une exception, elle est catchée et traduite (`404`, `500`, ect).

Et le cas plus tricky d'une _Command/Query_ : on crée un effet de bord mais on veut aussi renvoyer un _ReadModel_. Exemple on finalise une certification et on veut avoir les résultats : on produit des effets de bord (la certification devient inaccessible et on persiste des résultats) _**et**_ on renvoie aussi un _ReadModel_ (ex. pourcentage de réussite dans les différentes compétences). Ici il y a plusieurs façons de faire:
- Première façon de faire : ce que tu proposes. On prend la sortie du `usecase` et on le transforme dans la couche `infrastructure` en _ReadModel_ (via un `serializer` appelé dans le `controller` par exemple). Pour moi, dans le respect du principe de segregation des interfaces on ne doit pas renvoyer tout une grappe d'objets si on a seulement besoin d'une sous partie ce celle-ci pour générer le _ReadModel_. On peut pour cela renvoyer un _DomainEvent_ (ex. _CertificationCompletedEvent_). Le problème avec cette méthode c'est qu'on est tenté de faire transiter par le _usecase_ et donc par les objets du _domain_ des considérations liées au front. Par exemple : je vais avoir un objet _Badge_ (couche _domain_) qui contient un champs `imageUrl` (détail d'implémentation qui devrait être dans `infrastructure`) ou encore des listes d'objets `Session` (du `domain`) qui vont contenir des informations de pagination (idem).  D'où la deuxième façon de faire.

- Deuxième façon de faire : dans le _controller_, faire appel au `usecase` (_Command_) puis faire appel derrière à un _repository_ qui retourne un _ReadModel_.
```javascript
completeCertification(request) {
    await usecases.completeCertification(...);
    return certificationResultsReadModelRepository(...);
}
```
Parfois il y a besoin de passer quelques infos entre la sortie du `usecase` et l'entrée du `repository` de _ReadModels_ (ex. des ids de choses qui aurait été créées).

Avantage de la deuxième façon : on découple totalement les aspects métier utiles à l'écriture des aspects de présentation utiles à la lecture. 
Inconvénient potentiel : on peut avoir besoin de requêter plusieurs fois la BDD pour récupérer les même infos (une fois pour l'écriture et une fois pour la lecture) => il y a très probablement moyen d'optimiser ça ou bien de considérer ça comme un coût acceptable (c'est bien moins pire que de faire x appels différents depuis le front pour la même action par exemple).

**Comment by yahyayouness** [comment]
Je partage les avantages cités en dessus, l'utilisation des reads modèles dans Pix a permis d'optimiser le chargement de certains vues complexe et d'alléger la charge cognitive dans la lecture. Néanmoins attention à la synchronisation de ces reads modèles dans le front, l'utilisation des commandes qui altère la ressource coté serveur nécessite une synchronisation de ces read modèle. On se retrouve à devoir recharger la vue bind au read model à chaque mise à jour ... Avez vous rencontré ce problème et comment vous l'avez gérer ?

**Comment by EGI-OCTO** [comment]
@yahyayouness 
> Mon avis est que c'est acceptable en raison des avantages que ca apporte et vous ?

D'accord avec ça. En effet, je pense que ça mérite qu'on partage un snippet de code pour illustrer comment faire ça dans Ember (i.e. mettre à jour les read-models du store impactés par des appels sur d'autre ressources).

Je tente un exemple pour illustrer le problème (@yahyayouness tu me corriges si je tape à coté) : 
J'ai deux read-models, le premier `UserVisitCard` (qui contient seulement nom, prénom et e-mail) et le deuxième `UserDetailedProfile` (qui contient le profile entier avec : nom, prénom, e-mail, adresse, préférences de notifications, whatnot) si on appelle une route `/users/quelquechose` qui sert à modifier l'adresse e-mail du `user` comment mettre à jour les deux read-models correspondant coté Ember ?

**Comment by yahyayouness** [comment]
By separate models we most commonly mean different object models, probably running in different logical processes, perhaps on separate hardware. A web example would see a user looking at a web page that's rendered using the query model. If they initiate a change that change is routed to the separate command model for processing, the resulting change is communicated to the query model to render the updated state.

**Comment by sroccaserra** [comment]
Je ferme cette proposition, après plus d'un an d'inactivité je ne pense pas qu'elle soit encore utile.
